name: Blah test

on: [push]

jobs:
  # Job to run pre-checks
  pre-checks:
    name: "Blah test name"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
