name: Blah test

on:
  push:
    branches:
      - main

jobs:
  # Job to run pre-checks
  pre-checks:
    name: "Blah test name"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: sleep
        run: sleep 300
